default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development: &development
  <<: *default
  database: _short_url_development
  username: postgres
  password: dia-and-co-password
  host: localhost

test:
  <<: *development
  database: _short_url_test

production:
  url: <%= ENV['DATABASE_URL'] %>